### ISSUE TITLE
How to implement locally-windowed temporal self-attention?

### ISSUE THREAD

**Issue by GewelsJI** [hwjiang1510/VQLoC#1]
Hi @hwjiang1510 

Thanks for releasing a nice work. Could you provide more details about how to implement locally-windowed temporal self-attention in Spatio-Temporal Transformer? From your original description, it is hard to implement it.

Best.

**Comment by hwjiang1510** [comment]
Thanks for your interest in our work!

Feel free to shoot me an email and I can share the raw code.
