### ISSUE TITLE
Can share the raw code for learning? 

### ISSUE THREAD

**Issue by NorahGreen** [hwjiang1510/VQLoC#2]

**Comment by hwjiang1510** [comment]
Send me an email and I can share the raw code.

**Comment by NorahGreen** [comment]
***@***.***
Thank you for sharing the source code!&nbsp;


Best regards,
Yuqing Huang
21/07/2023


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hwjiang1510/VQLoC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月20日(星期四) 晚上10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hwjiang1510/VQLoC] Can share the raw code for learning?  (Issue #2)





 
Send me an email and I can share the raw code.
