### ISSUE TITLE
ARE there plans to release the code？

### ISSUE THREAD

**Issue by RainHxj** [hwjiang1510/VQLoC#3]

**Comment by hwjiang1510** [comment]
Hi, we are waiting for the submission reviews. Send me an email and I can share the raw code

**Comment by dreamerlin** [comment]
> Hi, we are waiting for the submission reviews. Send me an email and I can share the raw code

Same issue, and I have send an email for you. That would be helpful if you can share the raw code for me~

**Comment by RainHxj** [comment]
Thanks for your help. My email: xingjian.he@nlpr.ia.ac.cn
